#!/bin/sh

min_size=1000000
changed_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(geo)?json$")

compress_json() {
  file="$1"
  #size=$(stat --printf="%s" "$file")

  #if [ "$size" -gt "$min_size" ]; then
    echo "Compressing $file with Brotli..."
    brotli --force --keep "$file"
    git add "$file.br"
  #fi
}

for file in $changed_files; do
  compress_json "$file"
done

